apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-upload-service
  namespace: cloud-file-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-upload
  template:
    metadata:
      labels:
        app: file-upload
    spec:
      containers:
        - name: upload
          image: adityagiri1/cloud-file-processor-file-upload-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_URL
              value: http://eureka-service:8761/eureka
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka-service:9092
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/cloudfileprocessorv1
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres@123



