apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-processor-ingress
  namespace: cloud-file-processor
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: file-processor.local
      http:
        paths:
          - path: /upload(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: file-upload-service
                port:
                  number: 8081
          - path: /output(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: file-output-service
                port:
                  number: 8083

